### ISSUE TITLE
Custom Grammar don't load

### ISSUE THREAD

**Issue by thiagocarnaes** [azrijamilwt/odbc-driver#1]
I'm trying to load the custom grammar DB2, but the class ODBCDriverConnection doesn't find the class DB2.

If I comment the line 18, throw the follow error: 

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Foundation\Database\Driver\Grammars\DB2' not found","file":"D:\Apache\laravel\vendor\wajatimur\odbc-driver\src\Foundation\Database\Driver\ODBCDriverConnection.php","line":19}}

Any ideas to resolve this?

**Comment by azrijamilwt** [comment]
Loading custom grammar should be done in config file, could you share with we how do you load?

**Comment by thiagocarnaes** [comment]
'conn' => array(
     'driver' => 'odbc',
     'dsn' => 'my_con',
     'grammar' => 'DB2',
     'username' => 'user',
     'password' => 'passwd',
     'database' => 'my_db',
),

**Comment by azrijamilwt** [comment]
That a right way to load, so it seems that Laravel didn't found the file, can you verified that file exist at the said location in error stack.

**Comment by thiagocarnaes** [comment]
The file is in the folder:
D:\Apache\laravel\vendor\wajatimur\odbc-driver\src\Foundation\Database\Driver\Grammars\DB2.php

if I put the file DB2.php in the folder D:\Apache\laravel\vendor\laravel\framework\src\Illuminate\Database\Query\Grammars, the file load correctly
