### ISSUE TITLE
Using artisan migrate with ODBC 

### ISSUE THREAD

**Issue by lsnpatryks** [azrijamilwt/odbc-driver#2]
Function getDefaultSchemaGrammar in ODBCDriverConnection.php always tries to create instance of an abstract class Grammar. Isn't that a mistake? I added a same logic code as in function getDefaultQueryGrammar and provided a custom Grammar and then everything is correct (I prepared also a simple HP Vertica Schema grammar, which is basically PostgresGrammar with some corrections). Should I prepare a pull request?

**Comment by azrijamilwt** [comment]
Sounds good @lsnpatryks , i must be overlook on that. You are welcome on pull request. Anyway Big Thanks!
